addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.11")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("de.heikoseeberger"         % "sbt-header"          % "5.7.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"          % "4.1.1")
