name: Native Image

on:
  push:
    branches:
    - main
  pull_request:
  release:
    types: [published]

jobs:
  unix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        include:
        - os: macOS-latest
          uploaded_filename: rbr-favorites-sync-x86_64-apple-darwin
          local_path: ui/target/native-image/ui
        - os: ubuntu-latest
          uploaded_filename: rbr-favorites-sync-x86_64-pc-linux
          local_path: ui/target/native-image/ui
        - os: windows-latest
          uploaded_filename: rbr-favorites-sync-x86_64-pc-win32.exe
          local_path: ui/target/native-image/ui.exe
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: git fetch --tags || true
    - shell: bash
      if: ${{ matrix.os != 'windows-latest' }}
      run: sbt ui/nativeImage
    - shell: cmd
      if: ${{ matrix.os == 'windows-latest' }}
      run: >-
        "C:\Program Files\Microsoft Visual
        Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
        ui/nativeImage
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ matrix.local_path }}
        name: ${{ matrix.uploaded_filename }}
    - name: Upload release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ matrix.local_path }}
        asset_name: ${{ matrix.uploaded_filename }}
        asset_content_type: application/zip
