name: Native Image

on:
  push:
    branches:
    - main
  pull_request:
  release:
    types: [published]

jobs:
  native-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: ilammy/msvc-dev-cmd@v1
    - run: sbt clean ui/Universal/packageBin
    - run: mv ui/target/universal/rbr-favorites-sync-*.zip ui/target/universal/rbr-favorites-sync.zip
    - uses: actions/upload-artifact@v2
      with:
        path: ui/target/universal/rbr-favorites-sync.zip
        name: rbr-favorites-sync.zip
    - name: Upload release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ui/target/universal/rbr-favorites-sync.zip
        asset_name: rbr-favorites-sync.zip
        asset_content_type: application/zip
